version: '3.9'

services:
  java-challenge-api:
    container_name: java-challenge-api
    image: mvn:latest
    depends_on:
      - postgres-challenge-db
    ports:
      - "8080:8080"
    networks:
        internal-net:

  postgres-challenge-db:
        container_name: postgres-challenge-db
        image: postgres:13.4-alpine
        ports:
            - "5432:5432"
        restart: on-failure
        volumes:
            - challenge-volume:/var/lib/postgresql/data
        env_file:
            - postgres.dev.env
        networks:
            internal-net:

volumes:
    challenge-volume:
    challenge-maven-cache:

networks:
    internal-net:
        name: challenge-net